version: 2

jobs:
  build:

    docker:
        - image: gcc:5.5

    steps:
      - checkout
      - run: apt update
      - run: apt install -y zip
      - run: make prepare
      - run: make
      - run: make clean
      - run: make release
      - run:
          name: build stub release drivers
          command: |
              (cd release/sps30-uart
               make
               make clean)
      - run:
          name: build Linux release driver
          command: |
              (cd release/sps30-uart
               make uart_sources=sample-implementations/linux/sensirion_uart_implementation.c
               make clean)
